const GET_PRODUCTS= 'GET_PRODUCTS';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
// const GET_SINGLE_PRODUCTS= 'GET_SINGLE_PRODUCTS';
// const GET_SINGLE_PRODUCTS_SUCCESS = 'GET_SINGLE_PRODUCTS_SUCCESS';
// const GET_SINGLE_PRODUCTS_FAILURE = 'GET_SINGLE_PRODUCTS_FAILURE';

export {
    GET_PRODUCTS,
    GET_PRODUCTS_SUCCESS,
    GET_PRODUCTS_FAILURE,
    // GET_SINGLE_PRODUCTS,
    // GET_SINGLE_PRODUCTS_FAILURE,
    // GET_SINGLE_PRODUCTS_SUCCESS
};
