const GET_ARTICLE = 'GET_ARTICLE';
const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';
const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';
const GET_SINGLE_ARTICLE_SUCCESS = 'GET_SINGLE_ARTICLE_SUCCESS';
const GET_SINGLE_ARTICLE_FAILURE = 'GET_SINGLE_ARTICLE_FAILURE';

export {
    GET_ARTICLE,
    GET_ARTICLE_SUCCESS,
    GET_ARTICLE_FAILURE,
    GET_SINGLE_ARTICLE,
    GET_SINGLE_ARTICLE_FAILURE,
    GET_SINGLE_ARTICLE_SUCCESS
};
